/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleApprovalsRouteImport } from './routes/_console/approvals'
import { Route as ConsoleArtifactsRouteImport } from './routes/_console/artifacts'
import { Route as ConsoleAutomationsRouteImport } from './routes/_console/automations'
import { Route as ConsoleConnectionsRouteImport } from './routes/_console/connections'
import { Route as ConsoleControlRouteImport } from './routes/_console/control'
import { Route as ConsoleDecisionsRouteImport } from './routes/_console/decisions'
import { Route as ConsoleFleetRouteImport } from './routes/_console/fleet'
import { Route as ConsoleHubRouteImport } from './routes/_console/hub'
import { Route as ConsoleKnowledgeRouteImport } from './routes/_console/knowledge'
import { Route as ConsoleMemoryRouteImport } from './routes/_console/memory'
import { Route as ConsoleRadarRouteImport } from './routes/_console/radar'
import { Route as ConsoleResourcesRouteImport } from './routes/_console/resources'
import { Route as ConsoleSettingsRouteImport } from './routes/_console/settings'
import { Route as ConsoleMissionsIdRouteImport } from './routes/_console/missions/$id'
import { Route as ApiAjHooksRouteImport } from './routes/api/aj/hooks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleApprovalsRoute = ConsoleApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleArtifactsRoute = ConsoleArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAutomationsRoute = ConsoleAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleConnectionsRoute = ConsoleConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleControlRoute = ConsoleControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDecisionsRoute = ConsoleDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFleetRoute = ConsoleFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleHubRoute = ConsoleHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleKnowledgeRoute = ConsoleKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMemoryRoute = ConsoleMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRadarRoute = ConsoleRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleResourcesRoute = ConsoleResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMissionsIdRoute = ConsoleMissionsIdRouteImport.update({
  id: '/missions/$id',
  path: '/missions/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ApiAjHooksRoute = ApiAjHooksRouteImport.update({
  id: '/api/aj/hooks',
  path: '/api/aj/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/report': typeof ReportRoute
  '/approvals': typeof ConsoleApprovalsRoute
  '/artifacts': typeof ConsoleArtifactsRoute
  '/automations': typeof ConsoleAutomationsRoute
  '/connections': typeof ConsoleConnectionsRoute
  '/control': typeof ConsoleControlRoute
  '/decisions': typeof ConsoleDecisionsRoute
  '/fleet': typeof ConsoleFleetRoute
  '/hub': typeof ConsoleHubRoute
  '/knowledge': typeof ConsoleKnowledgeRoute
  '/memory': typeof ConsoleMemoryRoute
  '/radar': typeof ConsoleRadarRoute
  '/resources': typeof ConsoleResourcesRoute
  '/settings': typeof ConsoleSettingsRoute
  '/missions/$id': typeof ConsoleMissionsIdRoute
  '/api/aj/hooks': typeof ApiAjHooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/report': typeof ReportRoute
  '/approvals': typeof ConsoleApprovalsRoute
  '/artifacts': typeof ConsoleArtifactsRoute
  '/automations': typeof ConsoleAutomationsRoute
  '/connections': typeof ConsoleConnectionsRoute
  '/control': typeof ConsoleControlRoute
  '/decisions': typeof ConsoleDecisionsRoute
  '/fleet': typeof ConsoleFleetRoute
  '/hub': typeof ConsoleHubRoute
  '/knowledge': typeof ConsoleKnowledgeRoute
  '/memory': typeof ConsoleMemoryRoute
  '/radar': typeof ConsoleRadarRoute
  '/resources': typeof ConsoleResourcesRoute
  '/settings': typeof ConsoleSettingsRoute
  '/': typeof ConsoleIndexRoute
  '/missions/$id': typeof ConsoleMissionsIdRoute
  '/api/aj/hooks': typeof ApiAjHooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/report': typeof ReportRoute
  '/_console/approvals': typeof ConsoleApprovalsRoute
  '/_console/artifacts': typeof ConsoleArtifactsRoute
  '/_console/automations': typeof ConsoleAutomationsRoute
  '/_console/connections': typeof ConsoleConnectionsRoute
  '/_console/control': typeof ConsoleControlRoute
  '/_console/decisions': typeof ConsoleDecisionsRoute
  '/_console/fleet': typeof ConsoleFleetRoute
  '/_console/hub': typeof ConsoleHubRoute
  '/_console/knowledge': typeof ConsoleKnowledgeRoute
  '/_console/memory': typeof ConsoleMemoryRoute
  '/_console/radar': typeof ConsoleRadarRoute
  '/_console/resources': typeof ConsoleResourcesRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/missions/$id': typeof ConsoleMissionsIdRoute
  '/api/aj/hooks': typeof ApiAjHooksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/overlay'
    | '/report'
    | '/approvals'
    | '/artifacts'
    | '/automations'
    | '/connections'
    | '/control'
    | '/decisions'
    | '/fleet'
    | '/hub'
    | '/knowledge'
    | '/memory'
    | '/radar'
    | '/resources'
    | '/settings'
    | '/missions/$id'
    | '/api/aj/hooks'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/overlay'
    | '/report'
    | '/approvals'
    | '/artifacts'
    | '/automations'
    | '/connections'
    | '/control'
    | '/decisions'
    | '/fleet'
    | '/hub'
    | '/knowledge'
    | '/memory'
    | '/radar'
    | '/resources'
    | '/settings'
    | '/'
    | '/missions/$id'
    | '/api/aj/hooks'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_console'
    | '/login'
    | '/overlay'
    | '/report'
    | '/_console/approvals'
    | '/_console/artifacts'
    | '/_console/automations'
    | '/_console/connections'
    | '/_console/control'
    | '/_console/decisions'
    | '/_console/fleet'
    | '/_console/hub'
    | '/_console/knowledge'
    | '/_console/memory'
    | '/_console/radar'
    | '/_console/resources'
    | '/_console/settings'
    | '/_console/'
    | '/_console/missions/$id'
    | '/api/aj/hooks'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverlayRoute: typeof OverlayRoute
  ReportRoute: typeof ReportRoute
  ApiAjHooksRoute: typeof ApiAjHooksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/approvals': {
      id: '/_console/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ConsoleApprovalsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/artifacts': {
      id: '/_console/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ConsoleArtifactsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/automations': {
      id: '/_console/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ConsoleAutomationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/connections': {
      id: '/_console/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConsoleConnectionsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/control': {
      id: '/_console/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ConsoleControlRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/decisions': {
      id: '/_console/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof ConsoleDecisionsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/fleet': {
      id: '/_console/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof ConsoleFleetRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/hub': {
      id: '/_console/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof ConsoleHubRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/knowledge': {
      id: '/_console/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof ConsoleKnowledgeRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/memory': {
      id: '/_console/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof ConsoleMemoryRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/radar': {
      id: '/_console/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof ConsoleRadarRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/resources': {
      id: '/_console/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ConsoleResourcesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/missions/$id': {
      id: '/_console/missions/$id'
      path: '/missions/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof ConsoleMissionsIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/api/aj/hooks': {
      id: '/api/aj/hooks'
      path: '/api/aj/hooks'
      fullPath: '/api/aj/hooks'
      preLoaderRoute: typeof ApiAjHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleApprovalsRoute: typeof ConsoleApprovalsRoute
  ConsoleArtifactsRoute: typeof ConsoleArtifactsRoute
  ConsoleAutomationsRoute: typeof ConsoleAutomationsRoute
  ConsoleConnectionsRoute: typeof ConsoleConnectionsRoute
  ConsoleControlRoute: typeof ConsoleControlRoute
  ConsoleDecisionsRoute: typeof ConsoleDecisionsRoute
  ConsoleFleetRoute: typeof ConsoleFleetRoute
  ConsoleHubRoute: typeof ConsoleHubRoute
  ConsoleKnowledgeRoute: typeof ConsoleKnowledgeRoute
  ConsoleMemoryRoute: typeof ConsoleMemoryRoute
  ConsoleRadarRoute: typeof ConsoleRadarRoute
  ConsoleResourcesRoute: typeof ConsoleResourcesRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleMissionsIdRoute: typeof ConsoleMissionsIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleApprovalsRoute: ConsoleApprovalsRoute,
  ConsoleArtifactsRoute: ConsoleArtifactsRoute,
  ConsoleAutomationsRoute: ConsoleAutomationsRoute,
  ConsoleConnectionsRoute: ConsoleConnectionsRoute,
  ConsoleControlRoute: ConsoleControlRoute,
  ConsoleDecisionsRoute: ConsoleDecisionsRoute,
  ConsoleFleetRoute: ConsoleFleetRoute,
  ConsoleHubRoute: ConsoleHubRoute,
  ConsoleKnowledgeRoute: ConsoleKnowledgeRoute,
  ConsoleMemoryRoute: ConsoleMemoryRoute,
  ConsoleRadarRoute: ConsoleRadarRoute,
  ConsoleResourcesRoute: ConsoleResourcesRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleMissionsIdRoute: ConsoleMissionsIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
  OverlayRoute: OverlayRoute,
  ReportRoute: ReportRoute,
  ApiAjHooksRoute: ApiAjHooksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
